#!/usr/bin/env bash
# Configure nginx to return 301 on /redirect_me
STR="location /redirect_me {\n\t\treturn 301;\n\t}"
sed -i 's,# SSL configuration,'"$STR"',' /etc/nginx/sites-enabled/default
service nginx restart
