#!/usr/bin/env bash
# Configure nginx to return 301 on /redirect_me
RED="location /redirect_me {\n\t\treturn 301;\n\t}"
NTF="error_page 404 /cm_404.html;\n\tlocation = /cm_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
apt-get update
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i 's,# SSL configuration,'"$RED"',' /etc/nginx/sites-enabled/default
sed -i 's,# pass.*,'"$NTF"',' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/cm_404.html
service nginx start
