#!/usr/bin/env bash
#Changes nginx ports from 8080 to 80
sed -i 's/^.*listen 8080/\tlisten 80/' /etc/nginx/sites-enabled/default
sed -i 's/^.*listen \[::\]:8080/\tlisten [::]:80/' /etc/nginx/sites-enabled/default
service nginx restart
