#!/usr/bin/env bash
# Creates a file with It's PID, displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file created and terminates itself when receiving a SIGQUIT or SIGTERM signal
FILE=/var/run/holbertonscript.pid
trap "echo 'Y U no love me?!'" SIGINT
trap 'echo "I hate the kill command"; rm $FILE; exit' SIGTERM
trap 'rm $FILE; exit' SIGQUIT
pgrep -f "bash ./100-process_and_pid_file" > $FILE
while true
do
  echo "To infinity and beyond"
  sleep 2
done
