#!/usr/bin/env bash
# manages manage_my_process

##### Constants
SCRIPT=./manage_my_process
FILE=/var/run/my_process.pid

if [ ! $# -eq 1 ]
then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
fi

case $1 in
  "start")
    echo "manage_my_process started"
    $SCRIPT & disown
    echo $! > $FILE
    ;;
  "stop")
    echo "manage_my_process stopped"
    kill $(cat "$FILE")
    rm $FILE
    ;;
  "restart")
    echo "manage_my_process restarted"
    kill $(cat "$FILE")
    rm $FILE
    $SCRIPT & disown
    echo $! > $FILE
    ;;
esac
