#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
list=('Holberton School' "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School")
for i in "${list[@]}"; do
    echo $i;
done
