#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# Display hours from 0 to 12
# Display minutes from 1 to 59
h='0'
while [ $h -le 12 ]
do
  echo "Hour: ${h}"
  h=$((h + 1))
  m='1'
  while [ $m -lt 60 ]
  do
    echo $m
    m=$((m + 1))
  done
done
