#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# Display hours from 0 to 12
# Display minutes from 1 to 59
for h in {0..12}
do
  echo "Hour: ${h}"
  for m in {1..59}
  do
    echo $m
  done
done
