#!/usr/bin/env bash
# Bash script that displays the content of the current directory
# in a list format
# where only the part of the name after the first dash is displayed
LIST=$(ls)
for el in $LIST
do
  el=$(echo "$el" | cut -f2- -d "-")
  echo "$el"
done
