#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i s/^172.0.0.1/172.0.0.2/ ~/hosts.new
echo "8.8.8.8 facebook" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
