#!/usr/bin/env bash
#Starts nginx with user nginx
chmod 600 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx /usr/sbin/nginx
